version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FLASK_ENV: production
    ports:
      - "5000:5000"
    # environment:
    # - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json

  app_dev:
    container_name: news
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FLASK_ENV: development
    ports:
      - "5002:5000"
    networks:
      - custom_network
    volumes:
      - .:/app # Mount the current directory for hot reloading in development
    environment:
      # - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - FLASK_ENV=development
      - FLASK_DEBUG=1

networks:
  custom_network:
    external: true
